#! /bin/sh
# postinst script for opencbm

set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
        cfg=/etc/opencbm/opencbm-xa1541-modules-source.conf.h
	db_get opencbm-xa1541-modules-source/direct_port
	if $RET; then
		perl -p -i -e 's/^#.*(DIRECT_PORT_ACCESS).*$/#define $1/' $cfg
	else
		perl -p -i -e 's/^#.*(DIRECT_PORT_ACCESS).*$/#undef $1/' $cfg
	fi
fi

#DEBHELPER#

exit 0
