// ------------------------------------------------------------------------------
//<autogenerated>
//        This code was generated by Microsoft Visual Studio Team System 2005.
//
//        Changes to this file may cause incorrect behavior and will be lost if
//        the code is regenerated.
//</autogenerated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace PaytonByrd_ProcessConfigurationTests
{
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class BaseAccessor {
    
    protected Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject m_privateObject;
    
    protected BaseAccessor(object target, Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) {
        m_privateObject = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type);
    }
    
    protected BaseAccessor(Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) : 
            this(null, type) {
    }
    
    internal virtual object Target {
        get {
            return m_privateObject.Target;
        }
    }
    
    public override string ToString() {
        return this.Target.ToString();
    }
    
    public override bool Equals(object obj) {
        if (typeof(BaseAccessor).IsInstanceOfType(obj)) {
            obj = ((BaseAccessor)(obj)).Target;
        }
        return this.Target.Equals(obj);
    }
    
    public override int GetHashCode() {
        return this.Target.GetHashCode();
    }
}


[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class PaytonByrd_ProcessConfiguration_Helpers_ResourceHelperAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("PaytonByrd.ProcessConfiguration", "PaytonByrd.ProcessConfiguration.Helpers.ResourceHelper");
    
    internal PaytonByrd_ProcessConfiguration_Helpers_ResourceHelperAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal static string DEFAULT {
        get {
            string ret = ((string)(m_privateType.GetStaticField("DEFAULT")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DEFAULT", value);
        }
    }
    
    internal static string m_strUserCulture {
        get {
            string ret = ((string)(m_privateType.GetStaticField("m_strUserCulture")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("m_strUserCulture", value);
        }
    }
    
    internal static global::System.Resources.ResourceManager m_objResourceManager {
        get {
            global::System.Resources.ResourceManager ret = ((global::System.Resources.ResourceManager)(m_privateType.GetStaticField("m_objResourceManager")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("m_objResourceManager", value);
        }
    }
    
    internal static object CreatePrivate() {
        object[] args = new object[0];
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("PaytonByrd.ProcessConfiguration", "PaytonByrd.ProcessConfiguration.Helpers.ResourceHelper", new System.Type[0], args);
        return priv_obj.Target;
    }
    
    internal static string GetResource(string pv_strResourceName) {
        object[] args = new object[] {
                pv_strResourceName};
        string ret = ((string)(m_privateType.InvokeStatic("GetResource", new System.Type[] {
                    typeof(string)}, args)));
        return ret;
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class PaytonByrd_ProcessConfiguration_ProcessParameterAttributeAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("PaytonByrd.ProcessConfiguration", "PaytonByrd.ProcessConfiguration.ProcessParameterAttribute");
    
    internal PaytonByrd_ProcessConfiguration_ProcessParameterAttributeAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal static string CANNOT_BE_NULL_RESOURCE_ID {
        get {
            string ret = ((string)(m_privateType.GetStaticField("CANNOT_BE_NULL_RESOURCE_ID")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("CANNOT_BE_NULL_RESOURCE_ID", value);
        }
    }
    
    internal static string DOES_NOT_MATCH_EXPRESSION_RESOURCE_ID {
        get {
            string ret = ((string)(m_privateType.GetStaticField("DOES_NOT_MATCH_EXPRESSION_RESOURCE_ID")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DOES_NOT_MATCH_EXPRESSION_RESOURCE_ID", value);
        }
    }
    
    internal string m_strParameterName {
        get {
            string ret = ((string)(m_privateObject.GetField("m_strParameterName")));
            return ret;
        }
        set {
            m_privateObject.SetField("m_strParameterName", value);
        }
    }
    
    internal string m_strParameterAbbreviation {
        get {
            string ret = ((string)(m_privateObject.GetField("m_strParameterAbbreviation")));
            return ret;
        }
        set {
            m_privateObject.SetField("m_strParameterAbbreviation", value);
        }
    }
    
    internal bool m_blnParameterRequired {
        get {
            bool ret = ((bool)(m_privateObject.GetField("m_blnParameterRequired")));
            return ret;
        }
        set {
            m_privateObject.SetField("m_blnParameterRequired", value);
        }
    }
    
    internal string m_strValidationExpression {
        get {
            string ret = ((string)(m_privateObject.GetField("m_strValidationExpression")));
            return ret;
        }
        set {
            m_privateObject.SetField("m_strValidationExpression", value);
        }
    }
    
    internal string m_strParameterHelpResource {
        get {
            string ret = ((string)(m_privateObject.GetField("m_strParameterHelpResource")));
            return ret;
        }
        set {
            m_privateObject.SetField("m_strParameterHelpResource", value);
        }
    }
    
    internal static global::System.Attribute CreatePrivate(string pv_strParameterName, string pv_strParameterAbbreviation, bool pv_blnParameterRequired, string pv_strValidationExpression, string pv_strParameterHelpResource) {
        object[] args = new object[] {
                pv_strParameterName,
                pv_strParameterAbbreviation,
                pv_blnParameterRequired,
                pv_strValidationExpression,
                pv_strParameterHelpResource};
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("PaytonByrd.ProcessConfiguration", "PaytonByrd.ProcessConfiguration.ProcessParameterAttribute", new System.Type[] {
                    typeof(string),
                    typeof(string),
                    typeof(bool),
                    typeof(string),
                    typeof(string)}, args);
        return ((global::System.Attribute)(priv_obj.Target));
    }
    
    internal static global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor Validate(object pv_objInstance, global::System.Reflection.PropertyInfo pv_objPropertyInfo) {
        object[] args = new object[] {
                pv_objInstance,
                pv_objPropertyInfo};
        object _ret_val = m_privateType.InvokeStatic("Validate", new System.Type[] {
                    typeof(object),
                    typeof(global::System.Reflection.PropertyInfo)}, args);
        global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor _ret = null;
        if ((_ret_val != null)) {
            _ret = new global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor(_ret_val);
        }
        global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor ret = _ret;
        return ret;
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType("PaytonByrd.ProcessConfiguration", "PaytonByrd.ProcessConfiguration.ParameterValidationError");
    
    internal PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor(object target) : 
            base(target, m_privateType) {
    }
    
    internal bool IsValid {
        get {
            bool ret = ((bool)(m_privateObject.GetField("IsValid")));
            return ret;
        }
        set {
            m_privateObject.SetField("IsValid", value);
        }
    }
    
    internal string Description {
        get {
            string ret = ((string)(m_privateObject.GetField("Description")));
            return ret;
        }
        set {
            m_privateObject.SetField("Description", value);
        }
    }
    
    internal static object CreatePrivate() {
        object[] args = new object[0];
        Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject priv_obj = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject("PaytonByrd.ProcessConfiguration", "PaytonByrd.ProcessConfiguration.ParameterValidationError", new System.Type[0], args);
        return priv_obj.Target;
    }
    
    internal static global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor CreateValid() {
        object[] args = new object[0];
        object _ret_val = m_privateType.InvokeStatic("CreateValid", new System.Type[0], args);
        global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor _ret = null;
        if ((_ret_val != null)) {
            _ret = new global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor(_ret_val);
        }
        global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor ret = _ret;
        return ret;
    }
    
    internal static global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor CreateNotValid(string pv_strDescription) {
        object[] args = new object[] {
                pv_strDescription};
        object _ret_val = m_privateType.InvokeStatic("CreateNotValid", new System.Type[] {
                    typeof(string)}, args);
        global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor _ret = null;
        if ((_ret_val != null)) {
            _ret = new global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor(_ret_val);
        }
        global::PaytonByrd_ProcessConfigurationTests.PaytonByrd_ProcessConfiguration_ParameterValidationErrorAccessor ret = _ret;
        return ret;
    }
}
}
