RELATIVEPATH=../../
include ${RELATIVEPATH}LINUX/config.make
CFLAGS     := $(subst ../,../../,$(CFLAGS))
LINK_FLAGS := $(subst ../,../../,$(LINK_FLAGS))

PROG = frm_analyzer
INC  = frm_analyzer.inc

include ${RELATIVEPATH}LINUX/prgrules.make
